/* MBEL: The Microsoft Bytecode Engineering Library
 * Copyright (C) 2003 The University of Arizona
 * http://www.cs.arizona.edu/mbel/license.html
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */


package edu.arizona.cs.mbel.signature;

/**
 * Interface with constants for valid culture values
 *
 * @author Michael Stepp
 */
public interface Culture
{
	public static final String[] ValidCultures = {
			"ar-SA",
			"ar-IQ",
			"ar-EG",
			"ar-LY",
			"ar-DZ",
			"ar-MA",
			"ar-TN",
			"ar-OM",
			"ar-YE",
			"ar-SY",
			"ar-JO",
			"ar-LB",
			"ar-KW",
			"ar-AE",
			"ar-BH",
			"ar-QA",
			"bg-BG",
			"ca-ES",
			"zh-TW",
			"zh-CN",
			"zh-HK",
			"zh-SG",
			"zh-MO",
			"cs-CZ",
			"da-DK",
			"de-DE",
			"de-CH",
			"de-AT",
			"de-LU",
			"de-LI",
			"el-GR",
			"en-US",
			"en-GB",
			"en-AU",
			"en-CA",
			"en-NZ",
			"en-IE",
			"en-ZA",
			"en-JM",
			"en-CB",
			"en-BZ",
			"en-TT",
			"en-ZW",
			"en-PH",
			"es-ES-Ts",
			"es-MX",
			"es-ES-Is",
			"es-GT",
			"es-CR",
			"es-PA",
			"es-DO",
			"es-VE",
			"es-CO",
			"es-PE",
			"es-AR",
			"es-EC",
			"es-CL",
			"es-UY",
			"es-PY",
			"es-BO",
			"es-SV",
			"es-HN",
			"es-NI",
			"es-PR",
			"Fi-FI",
			"fr-FR",
			"fr-BE",
			"fr-CA",
			"Fr-CH",
			"fr-LU",
			"fr-MC",
			"he-IL",
			"hu-HU",
			"is-IS",
			"it-IT",
			"it-CH",
			"Ja-JP",
			"ko-KR",
			"nl-NL",
			"nl-BE",
			"nb-NO",
			"nn-NO",
			"pl-PL",
			"pt-BR",
			"pt-PT",
			"ro-RO",
			"ru-RU",
			"hr-HR",
			"Lt-sr-SP",
			"Cy-sr-SP",
			"sk-SK",
			"sq-AL",
			"sv-SE",
			"sv-FI",
			"th-TH",
			"tr-TR",
			"ur-PK",
			"id-ID",
			"uk-UA",
			"be-BY",
			"sl-SI",
			"et-EE",
			"lv-LV",
			"lt-LT",
			"fa-IR",
			"vi-VN",
			"hy-AM",
			"Lt-az-AZ",
			"Cy-az-AZ",
			"eu-ES",
			"mk-MK",
			"af-ZA",
			"ka-GE",
			"fo-FO",
			"hi-IN",
			"ms-MY",
			"ms-BN",
			"kk-KZ",
			"ky-KZ",
			"sw-KE",
			"Lt-uz-UZ",
			"Cy-uz-UZ",
			"tt-TA",
			"pa-IN",
			"gu-IN",
			"ta-IN",
			"te-IN",
			"kn-IN",
			"mr-IN",
			"sa-IN",
			"mn-MN",
			"gl-ES",
			"kok-IN",
			"syr-SY",
			"div-MV"
	};
}
