/* The following code was generated by JFlex 1.4.3 on 21.05.14 17:46 */

package org.mustbe.consulo.msil.lang.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import org.mustbe.consulo.msil.lang.psi.MsilTokens;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 21.05.14 17:46 from the specification file
 * <tt>H:/github.com/consulo/consulo-dotnet/msil-psi-impl/src/org/mustbe/consulo/msil/lang/lexer/_MsilLexer.flex</tt>
 */
public class _MsilLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\1\1\13\1\0\1\1\1\3\16\7\4\0\1\1\3\0"+
    "\1\6\1\0\1\26\1\12\1\23\1\24\1\4\1\0\1\27\1\0"+
    "\1\10\1\2\1\5\1\54\1\57\1\56\1\60\1\5\1\55\1\5"+
    "\1\53\1\5\1\20\1\0\1\16\1\25\1\17\2\0\32\6\1\21"+
    "\1\0\1\22\1\0\1\6\1\11\1\32\1\52\1\30\1\42\1\40"+
    "\1\43\1\61\1\41\1\44\1\62\1\6\1\31\1\37\1\51\1\36"+
    "\1\45\1\6\1\46\1\33\1\35\1\34\1\50\1\6\1\63\1\47"+
    "\1\64\1\14\1\0\1\15\1\0\41\7\2\0\4\6\4\0\1\6"+
    "\2\0\1\7\7\0\1\6\4\0\1\6\5\0\27\6\1\0\37\6"+
    "\1\0\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6\1\0\1\6"+
    "\21\0\160\7\5\6\1\0\2\6\2\0\4\6\10\0\1\6\1\0"+
    "\3\6\1\0\1\6\1\0\24\6\1\0\123\6\1\0\213\6\1\0"+
    "\5\7\2\0\236\6\11\0\46\6\2\0\1\6\7\0\47\6\7\0"+
    "\1\6\1\0\55\7\1\0\1\7\1\0\2\7\1\0\2\7\1\0"+
    "\1\7\10\0\33\6\5\0\3\6\15\0\5\7\6\0\1\6\4\0"+
    "\13\7\5\0\53\6\37\7\4\0\2\6\1\7\143\6\1\0\1\6"+
    "\10\7\1\0\6\7\2\6\2\7\1\0\4\7\2\6\12\7\3\6"+
    "\2\0\1\6\17\0\1\7\1\6\1\7\36\6\33\7\2\0\131\6"+
    "\13\7\1\6\16\0\12\7\41\6\11\7\2\6\4\0\1\6\5\0"+
    "\26\6\4\7\1\6\11\7\1\6\3\7\1\6\5\7\22\0\31\6"+
    "\3\7\104\0\1\6\1\0\13\6\67\0\33\7\1\0\4\7\66\6"+
    "\3\7\1\6\22\7\1\6\7\7\12\6\2\7\2\0\12\7\1\0"+
    "\7\6\1\0\7\6\1\0\3\7\1\0\10\6\2\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\1\6\3\0\4\6\2\0\1\7\1\6"+
    "\7\7\2\0\2\7\2\0\3\7\1\6\10\0\1\7\4\0\2\6"+
    "\1\0\3\6\2\7\2\0\12\7\4\6\7\0\1\6\5\0\3\7"+
    "\1\0\6\6\4\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6"+
    "\1\0\2\6\1\0\2\6\2\0\1\7\1\0\5\7\4\0\2\7"+
    "\2\0\3\7\3\0\1\7\7\0\4\6\1\0\1\6\7\0\14\7"+
    "\3\6\1\7\13\0\3\7\1\0\11\6\1\0\3\6\1\0\26\6"+
    "\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6\10\7"+
    "\1\0\3\7\1\0\3\7\2\0\1\6\17\0\2\6\2\7\2\0"+
    "\12\7\1\0\1\6\17\0\3\7\1\0\10\6\2\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6"+
    "\7\7\2\0\2\7\2\0\3\7\10\0\2\7\4\0\2\6\1\0"+
    "\3\6\2\7\2\0\12\7\1\0\1\6\20\0\1\7\1\6\1\0"+
    "\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6\1\0"+
    "\2\6\3\0\2\6\3\0\3\6\3\0\14\6\4\0\5\7\3\0"+
    "\3\7\1\0\4\7\2\0\1\6\6\0\1\7\16\0\12\7\11\0"+
    "\1\6\7\0\3\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0"+
    "\12\6\1\0\5\6\3\0\1\6\7\7\1\0\3\7\1\0\4\7"+
    "\7\0\2\7\1\0\2\6\6\0\2\6\2\7\2\0\12\7\22\0"+
    "\2\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0"+
    "\5\6\2\0\1\7\1\6\7\7\1\0\3\7\1\0\4\7\7\0"+
    "\2\7\7\0\1\6\1\0\2\6\2\7\2\0\12\7\1\0\2\6"+
    "\17\0\2\7\1\0\10\6\1\0\3\6\1\0\51\6\2\0\1\6"+
    "\7\7\1\0\3\7\1\0\4\7\1\6\10\0\1\7\10\0\2\6"+
    "\2\7\2\0\12\7\12\0\6\6\2\0\2\7\1\0\22\6\3\0"+
    "\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\7\4\0"+
    "\6\7\1\0\1\7\1\0\10\7\22\0\2\7\15\0\60\6\1\7"+
    "\2\6\7\7\4\0\10\6\10\7\1\0\12\7\47\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6\1\0"+
    "\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6\1\0"+
    "\4\6\1\7\2\6\6\7\1\0\2\7\1\6\2\0\5\6\1\0"+
    "\1\6\1\0\6\7\2\0\12\7\2\0\4\6\40\0\1\6\27\0"+
    "\2\7\6\0\12\7\13\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\10\6\1\0\44\6\4\0\24\7\1\0\2\7\5\6\13\7"+
    "\1\0\44\7\11\0\1\7\71\0\53\6\24\7\1\6\12\7\6\0"+
    "\6\6\4\7\4\6\3\7\1\6\3\7\2\6\7\7\3\6\4\7"+
    "\15\6\14\7\1\6\17\7\2\0\46\6\1\0\1\6\5\0\1\6"+
    "\2\0\53\6\1\0\u014d\6\1\0\4\6\2\0\7\6\1\0\1\6"+
    "\1\0\4\6\2\0\51\6\1\0\4\6\2\0\41\6\1\0\4\6"+
    "\2\0\7\6\1\0\1\6\1\0\4\6\2\0\17\6\1\0\71\6"+
    "\1\0\4\6\2\0\103\6\2\0\3\7\40\0\20\6\20\0\125\6"+
    "\14\0\u026c\6\2\0\21\6\1\0\32\6\5\0\113\6\3\0\3\6"+
    "\17\0\15\6\1\0\4\6\3\7\13\0\22\6\3\7\13\0\22\6"+
    "\2\7\14\0\15\6\1\0\3\6\1\0\2\7\14\0\64\6\40\7"+
    "\3\0\1\6\3\0\2\6\1\7\2\0\12\7\41\0\3\7\2\0"+
    "\12\7\6\0\130\6\10\0\51\6\1\7\1\6\5\0\106\6\12\0"+
    "\35\6\3\0\14\7\4\0\14\7\12\0\12\7\36\6\2\0\5\6"+
    "\13\0\54\6\4\0\21\7\7\6\2\7\6\0\12\7\46\0\27\6"+
    "\5\7\4\0\65\6\12\7\1\0\35\7\2\0\13\7\6\0\12\7"+
    "\15\0\1\6\130\0\5\7\57\6\21\7\7\6\4\0\12\7\21\0"+
    "\11\7\14\0\3\7\36\6\15\7\2\6\12\7\54\6\16\7\14\0"+
    "\44\6\24\7\10\0\12\7\3\0\3\6\12\7\44\6\122\0\3\7"+
    "\1\0\25\7\4\6\1\7\4\6\3\7\2\6\11\0\300\6\47\7"+
    "\25\0\4\7\u0116\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0"+
    "\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0"+
    "\65\6\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0"+
    "\4\6\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\16\0"+
    "\5\7\32\0\5\7\20\0\2\6\23\0\1\6\13\0\5\7\5\0"+
    "\6\7\1\0\1\6\15\0\1\6\20\0\15\6\3\0\33\6\25\0"+
    "\15\7\4\0\1\7\3\0\14\7\21\0\1\6\4\0\1\6\2\0"+
    "\12\6\1\0\1\6\3\0\5\6\6\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\4\6\1\0\13\6\2\0\4\6\5\0\5\6\4\0"+
    "\1\6\21\0\51\6\u0a77\0\57\6\1\0\57\6\1\0\205\6\6\0"+
    "\4\6\3\7\2\6\14\0\46\6\1\0\1\6\5\0\1\6\2\0"+
    "\70\6\7\0\1\6\17\0\1\7\27\6\11\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\40\7\57\0\1\6\u01d5\0\3\6\31\0\11\6"+
    "\6\7\1\0\5\6\2\0\5\6\4\0\126\6\2\0\2\7\2\0"+
    "\3\6\1\0\132\6\1\0\4\6\5\0\51\6\3\0\136\6\21\0"+
    "\33\6\65\0\20\6\u0200\0\u19b6\6\112\0\u51cd\6\63\0\u048d\6\103\0"+
    "\56\6\2\0\u010d\6\3\0\20\6\12\7\2\6\24\0\57\6\1\7"+
    "\4\0\12\7\1\0\31\6\7\0\1\7\120\6\2\7\45\0\11\6"+
    "\2\0\147\6\2\0\4\6\1\0\4\6\14\0\13\6\115\0\12\6"+
    "\1\7\3\6\1\7\4\6\1\7\27\6\5\7\20\0\1\6\7\0"+
    "\64\6\14\0\2\7\62\6\21\7\13\0\12\7\6\0\22\7\6\6"+
    "\3\0\1\6\4\0\12\7\34\6\10\7\2\0\27\6\15\7\14\0"+
    "\35\6\3\0\4\7\57\6\16\7\16\0\1\6\12\7\46\0\51\6"+
    "\16\7\11\0\3\6\1\7\10\6\2\7\2\0\12\7\6\0\27\6"+
    "\3\0\1\6\1\7\4\0\60\6\1\7\1\6\3\7\2\6\2\7"+
    "\5\6\2\7\1\6\1\7\1\6\30\0\3\6\2\0\13\6\5\7"+
    "\2\0\3\6\2\7\12\0\6\6\2\0\6\6\2\0\6\6\11\0"+
    "\7\6\1\0\7\6\221\0\43\6\10\7\1\0\2\7\2\0\12\7"+
    "\6\0\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0\u016e\6\2\0\152\6"+
    "\46\0\7\6\14\0\5\6\5\0\1\6\1\7\12\6\1\0\15\6"+
    "\1\0\5\6\1\0\1\6\1\0\2\6\1\0\2\6\1\0\154\6"+
    "\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0\15\6\3\0\20\7"+
    "\20\0\7\7\14\0\2\6\30\0\3\6\31\0\1\6\6\0\5\6"+
    "\1\0\207\6\2\0\1\7\4\0\1\6\13\0\12\7\7\0\32\6"+
    "\4\0\1\6\1\0\32\6\13\0\131\6\3\0\6\6\2\0\6\6"+
    "\2\0\6\6\2\0\3\6\3\0\2\6\3\0\2\6\22\0\3\7"+
    "\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\2\1"+
    "\1\6\1\7\1\10\1\11\1\1\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\15\5\1\21\1\22\1\0"+
    "\7\5\1\0\1\23\1\24\1\0\26\5\1\0\10\5"+
    "\1\0\32\5\1\22\10\5\1\0\1\5\1\25\20\5"+
    "\1\26\10\5\1\27\1\5\1\30\10\5\1\31\1\32"+
    "\10\5\1\33\6\5\1\34\1\35\2\5\1\36\1\37"+
    "\1\40\4\5\1\41\1\5\1\42\3\5\1\43\1\44"+
    "\1\45\4\5\1\46\1\47\1\50\2\5\1\51\1\52"+
    "\1\53\1\54\6\5\1\55\4\5\1\56\1\5\1\57"+
    "\1\5\1\60\4\5\1\61\1\5\1\62\4\5\1\63"+
    "\1\5\1\64\2\5\1\65\1\66\5\5\1\67\2\5"+
    "\1\70\1\71\2\5\1\72\1\5\1\73\1\74\1\75"+
    "\2\5\1\76\1\5\1\77\1\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[261];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\65\0\65\0\324\0\u0109"+
    "\0\u013e\0\65\0\65\0\65\0\65\0\u0173\0\u01a8\0\65"+
    "\0\65\0\65\0\65\0\65\0\65\0\u01dd\0\u0212\0\u0247"+
    "\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef"+
    "\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597"+
    "\0\u05cc\0\u0601\0\u0636\0\u066b\0\u013e\0\u013e\0\65\0\u06a0"+
    "\0\u06d5\0\u070a\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813\0\u0848"+
    "\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0"+
    "\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\u0b98"+
    "\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40"+
    "\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8"+
    "\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b\0\u1090"+
    "\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203\0\u1238"+
    "\0\u126d\0\u12a2\0\65\0\u12d7\0\u130c\0\u1341\0\u1376\0\u13ab"+
    "\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4\0\324\0\u14e9\0\u151e"+
    "\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c\0\u1691\0\u16c6"+
    "\0\u16fb\0\u1730\0\u1765\0\u179a\0\u17cf\0\u1804\0\324\0\u1839"+
    "\0\u186e\0\u18a3\0\u18d8\0\u190d\0\u1942\0\u1977\0\u19ac\0\324"+
    "\0\u19e1\0\324\0\u1a16\0\u1a4b\0\u1a80\0\u1ab5\0\u1aea\0\u1b1f"+
    "\0\u1b54\0\u1b89\0\65\0\324\0\u1bbe\0\u1bf3\0\u1c28\0\u1c5d"+
    "\0\u1c92\0\u1cc7\0\u1cfc\0\u1d31\0\324\0\u1d66\0\u1d9b\0\u1dd0"+
    "\0\u1e05\0\u1e3a\0\u1e6f\0\u1ea4\0\324\0\u1ed9\0\u1f0e\0\324"+
    "\0\324\0\324\0\u1f43\0\u1f78\0\u1fad\0\u1fe2\0\u2017\0\u204c"+
    "\0\324\0\u2081\0\u20b6\0\u20eb\0\324\0\324\0\324\0\u2120"+
    "\0\u2155\0\u218a\0\u21bf\0\324\0\324\0\324\0\u21f4\0\u2229"+
    "\0\324\0\324\0\324\0\324\0\u225e\0\u2293\0\u22c8\0\u22fd"+
    "\0\u2332\0\u2367\0\324\0\u239c\0\u23d1\0\u2406\0\u243b\0\324"+
    "\0\u2470\0\324\0\u24a5\0\324\0\u24da\0\u250f\0\u2544\0\u2579"+
    "\0\324\0\u25ae\0\324\0\u25e3\0\u2618\0\u264d\0\u2682\0\324"+
    "\0\u26b7\0\324\0\u26ec\0\u2721\0\324\0\324\0\u2756\0\u278b"+
    "\0\u27c0\0\u27f5\0\u282a\0\324\0\u285f\0\u2894\0\324\0\324"+
    "\0\u28c9\0\u28fe\0\324\0\u2933\0\324\0\324\0\324\0\u2968"+
    "\0\u299d\0\324\0\u29d2\0\324\0\324";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[261];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\5\1\6\1\7\1\2"+
    "\1\10\1\2\1\11\1\3\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\7\1\33\1\7"+
    "\1\34\1\35\1\7\1\36\1\37\1\40\2\7\1\41"+
    "\1\7\1\42\6\6\4\7\66\0\1\3\1\0\1\3"+
    "\7\0\1\3\53\0\1\43\1\0\1\44\65\0\3\7"+
    "\1\45\1\46\16\0\35\7\6\0\1\7\21\0\1\47"+
    "\1\7\1\50\4\7\1\51\1\52\2\7\1\53\1\7"+
    "\1\54\5\7\6\0\4\7\12\55\1\56\1\0\51\55"+
    "\20\0\1\57\102\0\1\60\33\0\3\7\1\45\1\46"+
    "\16\0\1\7\1\61\7\7\1\62\23\7\5\0\3\7"+
    "\1\45\1\46\16\0\14\7\1\63\20\7\5\0\3\7"+
    "\1\45\1\46\16\0\3\7\1\64\16\7\1\65\12\7"+
    "\5\0\3\7\1\45\1\46\16\0\5\7\1\66\2\7"+
    "\1\67\4\7\1\70\17\7\5\0\3\7\1\45\1\46"+
    "\16\0\14\7\1\71\20\7\5\0\3\7\1\45\1\46"+
    "\16\0\22\7\1\72\12\7\5\0\3\7\1\45\1\46"+
    "\16\0\33\7\1\73\1\7\5\0\3\7\1\45\1\46"+
    "\16\0\14\7\1\74\20\7\5\0\3\7\1\45\1\46"+
    "\16\0\1\7\1\75\12\7\1\76\20\7\5\0\3\7"+
    "\1\45\1\46\16\0\7\7\1\77\11\7\1\100\13\7"+
    "\5\0\3\7\1\45\1\46\16\0\4\7\1\101\11\7"+
    "\1\102\16\7\5\0\3\7\1\45\1\46\16\0\2\7"+
    "\1\103\3\7\1\104\5\7\1\105\20\7\5\0\3\7"+
    "\1\45\1\46\16\0\6\7\1\106\26\7\3\43\1\0"+
    "\7\43\1\0\51\43\4\44\1\107\60\44\6\0\1\7"+
    "\21\0\23\7\6\0\4\7\5\0\3\46\20\0\35\46"+
    "\5\0\3\7\1\45\1\46\16\0\1\7\1\110\2\7"+
    "\1\111\30\7\5\0\3\7\1\45\1\46\16\0\3\7"+
    "\1\112\31\7\5\0\3\7\1\45\1\46\16\0\10\7"+
    "\1\113\24\7\5\0\3\7\1\45\1\46\16\0\20\7"+
    "\1\114\14\7\5\0\3\7\1\45\1\46\16\0\14\7"+
    "\1\115\20\7\5\0\3\7\1\45\1\46\16\0\2\7"+
    "\1\116\13\7\1\117\16\7\34\0\1\120\35\0\3\7"+
    "\1\45\1\46\16\0\2\7\1\121\32\7\5\0\3\7"+
    "\1\45\1\46\16\0\2\7\1\122\32\7\5\0\3\7"+
    "\1\45\1\46\16\0\5\7\1\123\27\7\5\0\3\7"+
    "\1\45\1\46\16\0\3\7\1\124\31\7\5\0\3\7"+
    "\1\45\1\46\16\0\3\7\1\125\31\7\5\0\3\7"+
    "\1\45\1\46\16\0\2\7\1\126\13\7\1\127\16\7"+
    "\5\0\3\7\1\45\1\46\16\0\2\7\1\130\13\7"+
    "\1\131\16\7\5\0\3\7\1\45\1\46\16\0\10\7"+
    "\1\132\24\7\5\0\3\7\1\45\1\46\16\0\21\7"+
    "\1\133\13\7\5\0\3\7\1\45\1\46\16\0\32\7"+
    "\1\134\2\7\5\0\3\7\1\45\1\46\16\0\5\7"+
    "\1\135\27\7\5\0\3\7\1\45\1\46\16\0\12\7"+
    "\1\136\22\7\5\0\3\7\1\45\1\46\16\0\6\7"+
    "\1\137\26\7\5\0\3\7\1\45\1\46\16\0\21\7"+
    "\1\140\13\7\5\0\3\7\1\45\1\46\16\0\15\7"+
    "\1\141\17\7\5\0\3\7\1\45\1\46\16\0\5\7"+
    "\1\142\6\7\1\143\20\7\5\0\3\7\1\45\1\46"+
    "\16\0\22\7\1\144\12\7\5\0\3\7\1\45\1\46"+
    "\16\0\6\7\1\145\5\7\1\146\20\7\5\0\3\7"+
    "\1\45\1\46\16\0\1\7\1\147\33\7\5\0\3\7"+
    "\1\45\1\46\16\0\14\7\1\150\20\7\5\0\3\7"+
    "\1\45\1\46\16\0\16\7\1\151\16\7\5\0\3\7"+
    "\1\45\1\46\16\0\6\7\1\152\26\7\2\44\1\153"+
    "\1\44\1\107\60\44\5\0\3\7\1\45\1\46\16\0"+
    "\2\7\1\154\32\7\5\0\3\7\1\45\1\46\16\0"+
    "\3\7\1\155\31\7\5\0\3\7\1\45\1\46\16\0"+
    "\3\7\1\156\31\7\5\0\3\7\1\45\1\46\16\0"+
    "\5\7\1\157\27\7\5\0\3\7\1\45\1\46\16\0"+
    "\10\7\1\160\24\7\5\0\3\7\1\45\1\46\16\0"+
    "\10\7\1\161\24\7\5\0\3\7\1\45\1\46\16\0"+
    "\16\7\1\162\16\7\5\0\3\7\1\45\1\46\16\0"+
    "\6\7\1\163\26\7\35\0\1\164\34\0\3\7\1\45"+
    "\1\46\16\0\3\7\1\165\31\7\5\0\3\7\1\45"+
    "\1\46\16\0\16\7\1\166\16\7\5\0\3\7\1\45"+
    "\1\46\16\0\10\7\1\167\24\7\5\0\3\7\1\45"+
    "\1\46\16\0\10\7\1\170\24\7\5\0\3\7\1\45"+
    "\1\46\16\0\5\7\1\171\27\7\5\0\3\7\1\45"+
    "\1\46\16\0\5\7\1\172\27\7\5\0\3\7\1\45"+
    "\1\46\16\0\14\7\1\173\20\7\5\0\3\7\1\45"+
    "\1\46\16\0\1\7\1\174\33\7\5\0\3\7\1\45"+
    "\1\46\16\0\14\7\1\175\20\7\5\0\3\7\1\45"+
    "\1\46\16\0\1\176\34\7\5\0\3\7\1\45\1\46"+
    "\16\0\5\7\1\177\27\7\5\0\3\7\1\45\1\46"+
    "\16\0\10\7\1\200\24\7\5\0\3\7\1\45\1\46"+
    "\16\0\10\7\1\201\24\7\5\0\3\7\1\45\1\46"+
    "\16\0\10\7\1\202\24\7\5\0\3\7\1\45\1\46"+
    "\16\0\2\7\1\203\32\7\5\0\3\7\1\45\1\46"+
    "\16\0\2\7\1\204\32\7\5\0\3\7\1\45\1\46"+
    "\16\0\1\7\1\205\33\7\5\0\3\7\1\45\1\46"+
    "\16\0\10\7\1\206\12\7\1\207\1\210\1\211\1\212"+
    "\6\7\5\0\3\7\1\45\1\46\16\0\5\7\1\213"+
    "\27\7\5\0\3\7\1\45\1\46\16\0\1\7\1\214"+
    "\33\7\5\0\3\7\1\45\1\46\16\0\5\7\1\215"+
    "\27\7\5\0\3\7\1\45\1\46\16\0\20\7\1\216"+
    "\14\7\5\0\3\7\1\45\1\46\16\0\4\7\1\217"+
    "\30\7\5\0\3\7\1\45\1\46\16\0\12\7\1\220"+
    "\22\7\5\0\3\7\1\45\1\46\16\0\5\7\1\221"+
    "\27\7\5\0\3\7\1\45\1\46\16\0\1\7\1\222"+
    "\33\7\5\0\3\7\1\45\1\46\16\0\3\7\1\223"+
    "\31\7\5\0\3\7\1\45\1\46\16\0\5\7\1\224"+
    "\27\7\5\0\3\7\1\45\1\46\16\0\10\7\1\225"+
    "\24\7\5\0\3\7\1\45\1\46\16\0\11\7\1\226"+
    "\23\7\5\0\3\7\1\45\1\46\16\0\21\7\1\227"+
    "\13\7\5\0\3\7\1\45\1\46\16\0\1\7\1\230"+
    "\33\7\5\0\3\7\1\45\1\46\16\0\2\7\1\231"+
    "\32\7\5\0\3\7\1\45\1\46\16\0\15\7\1\232"+
    "\17\7\22\0\1\233\47\0\3\7\1\45\1\46\16\0"+
    "\3\7\1\234\31\7\5\0\3\7\1\45\1\46\16\0"+
    "\16\7\1\235\16\7\5\0\3\7\1\45\1\46\16\0"+
    "\7\7\1\236\25\7\5\0\3\7\1\45\1\46\16\0"+
    "\16\7\1\237\16\7\5\0\3\7\1\45\1\46\16\0"+
    "\14\7\1\240\20\7\5\0\3\7\1\45\1\46\16\0"+
    "\21\7\1\241\13\7\5\0\3\7\1\45\1\46\16\0"+
    "\10\7\1\242\24\7\5\0\3\7\1\45\1\46\16\0"+
    "\2\7\1\243\32\7\5\0\3\7\1\45\1\46\16\0"+
    "\14\7\1\244\20\7\5\0\3\7\1\45\1\46\16\0"+
    "\23\7\1\245\1\246\1\247\1\250\6\7\5\0\3\7"+
    "\1\45\1\46\16\0\1\251\34\7\5\0\3\7\1\45"+
    "\1\46\16\0\21\7\1\252\13\7\5\0\3\7\1\45"+
    "\1\46\16\0\22\7\1\253\12\7\5\0\3\7\1\45"+
    "\1\46\16\0\5\7\1\254\27\7\5\0\3\7\1\45"+
    "\1\46\16\0\1\7\1\255\33\7\5\0\3\7\1\45"+
    "\1\46\16\0\10\7\1\256\24\7\5\0\3\7\1\45"+
    "\1\46\16\0\16\7\1\257\16\7\5\0\3\7\1\45"+
    "\1\46\16\0\25\7\1\260\7\7\5\0\3\7\1\45"+
    "\1\46\16\0\30\7\1\261\4\7\5\0\3\7\1\45"+
    "\1\46\16\0\27\7\1\262\5\7\5\0\3\7\1\45"+
    "\1\46\16\0\6\7\1\263\26\7\5\0\3\7\1\45"+
    "\1\46\16\0\14\7\1\264\20\7\5\0\3\7\1\45"+
    "\1\46\16\0\10\7\1\265\24\7\5\0\3\7\1\45"+
    "\1\46\16\0\2\7\1\266\32\7\5\0\3\7\1\45"+
    "\1\46\16\0\10\7\1\267\24\7\5\0\3\7\1\45"+
    "\1\46\16\0\4\7\1\270\30\7\5\0\3\7\1\45"+
    "\1\46\16\0\3\7\1\271\31\7\5\0\3\7\1\45"+
    "\1\46\16\0\6\7\1\272\26\7\5\0\3\7\1\45"+
    "\1\46\16\0\7\7\1\273\25\7\5\0\3\7\1\45"+
    "\1\46\16\0\6\7\1\274\26\7\5\0\3\7\1\45"+
    "\1\46\16\0\5\7\1\275\27\7\5\0\3\7\1\45"+
    "\1\46\16\0\12\7\1\276\22\7\5\0\3\7\1\45"+
    "\1\46\16\0\7\7\1\277\25\7\5\0\3\7\1\45"+
    "\1\46\16\0\10\7\1\300\24\7\5\0\3\7\1\45"+
    "\1\46\16\0\2\7\1\301\32\7\5\0\3\7\1\45"+
    "\1\46\16\0\22\7\1\302\12\7\5\0\3\7\1\45"+
    "\1\46\16\0\2\7\1\303\32\7\5\0\3\7\1\45"+
    "\1\46\16\0\1\304\34\7\5\0\3\7\1\45\1\46"+
    "\16\0\31\7\1\305\3\7\5\0\3\7\1\45\1\46"+
    "\16\0\12\7\1\306\22\7\5\0\3\7\1\45\1\46"+
    "\16\0\1\7\1\307\33\7\5\0\3\7\1\45\1\46"+
    "\16\0\2\7\1\310\32\7\5\0\3\7\1\45\1\46"+
    "\16\0\25\7\1\311\7\7\5\0\3\7\1\45\1\46"+
    "\16\0\30\7\1\312\4\7\5\0\3\7\1\45\1\46"+
    "\16\0\27\7\1\313\5\7\5\0\3\7\1\45\1\46"+
    "\16\0\5\7\1\314\27\7\5\0\3\7\1\45\1\46"+
    "\16\0\12\7\1\315\22\7\5\0\3\7\1\45\1\46"+
    "\16\0\17\7\1\316\15\7\5\0\3\7\1\45\1\46"+
    "\16\0\25\7\1\317\7\7\5\0\3\7\1\45\1\46"+
    "\16\0\7\7\1\320\25\7\5\0\3\7\1\45\1\46"+
    "\16\0\13\7\1\321\21\7\5\0\3\7\1\45\1\46"+
    "\16\0\21\7\1\322\13\7\5\0\3\7\1\45\1\46"+
    "\16\0\1\323\34\7\5\0\3\7\1\45\1\46\16\0"+
    "\1\324\34\7\5\0\3\7\1\45\1\46\16\0\5\7"+
    "\1\325\27\7\5\0\3\7\1\45\1\46\16\0\5\7"+
    "\1\326\27\7\5\0\3\7\1\45\1\46\16\0\2\7"+
    "\1\327\32\7\5\0\3\7\1\45\1\46\16\0\7\7"+
    "\1\330\25\7\5\0\3\7\1\45\1\46\16\0\22\7"+
    "\1\331\12\7\5\0\3\7\1\45\1\46\16\0\12\7"+
    "\1\332\22\7\5\0\3\7\1\45\1\46\16\0\16\7"+
    "\1\333\16\7\5\0\3\7\1\45\1\46\16\0\1\7"+
    "\1\334\33\7\5\0\3\7\1\45\1\46\16\0\1\7"+
    "\1\335\33\7\5\0\3\7\1\45\1\46\16\0\1\336"+
    "\34\7\5\0\3\7\1\45\1\46\16\0\14\7\1\337"+
    "\20\7\5\0\3\7\1\45\1\46\16\0\1\7\1\340"+
    "\33\7\5\0\3\7\1\45\1\46\16\0\3\7\1\341"+
    "\31\7\5\0\3\7\1\45\1\46\16\0\3\7\1\342"+
    "\31\7\5\0\3\7\1\45\1\46\16\0\30\7\1\343"+
    "\4\7\5\0\3\7\1\45\1\46\16\0\10\7\1\344"+
    "\24\7\5\0\3\7\1\45\1\46\16\0\2\7\1\345"+
    "\32\7\5\0\3\7\1\45\1\46\16\0\1\7\1\346"+
    "\33\7\5\0\3\7\1\45\1\46\16\0\5\7\1\347"+
    "\27\7\5\0\3\7\1\45\1\46\16\0\10\7\1\350"+
    "\24\7\5\0\3\7\1\45\1\46\16\0\17\7\1\351"+
    "\15\7\5\0\3\7\1\45\1\46\16\0\1\7\1\352"+
    "\33\7\5\0\3\7\1\45\1\46\16\0\1\7\1\353"+
    "\33\7\5\0\3\7\1\45\1\46\16\0\5\7\1\354"+
    "\27\7\5\0\3\7\1\45\1\46\16\0\17\7\1\355"+
    "\15\7\5\0\3\7\1\45\1\46\16\0\5\7\1\356"+
    "\27\7\5\0\3\7\1\45\1\46\16\0\34\7\1\357"+
    "\5\0\3\7\1\45\1\46\16\0\21\7\1\360\13\7"+
    "\5\0\3\7\1\45\1\46\16\0\14\7\1\361\20\7"+
    "\5\0\3\7\1\45\1\46\16\0\21\7\1\362\13\7"+
    "\5\0\3\7\1\45\1\46\16\0\1\363\34\7\5\0"+
    "\3\7\1\45\1\46\16\0\17\7\1\364\15\7\5\0"+
    "\3\7\1\45\1\46\16\0\10\7\1\365\24\7\5\0"+
    "\3\7\1\45\1\46\16\0\15\7\1\366\17\7\5\0"+
    "\3\7\1\45\1\46\16\0\17\7\1\367\15\7\5\0"+
    "\3\7\1\45\1\46\16\0\17\7\1\370\15\7\5\0"+
    "\3\7\1\45\1\46\16\0\2\7\1\371\32\7\5\0"+
    "\3\7\1\45\1\46\16\0\2\7\1\372\32\7\5\0"+
    "\3\7\1\45\1\46\16\0\31\7\1\373\3\7\5\0"+
    "\3\7\1\45\1\46\16\0\5\7\1\374\27\7\5\0"+
    "\3\7\1\45\1\46\16\0\10\7\1\375\24\7\5\0"+
    "\3\7\1\45\1\46\16\0\12\7\1\376\22\7\5\0"+
    "\3\7\1\45\1\46\16\0\10\7\1\377\24\7\5\0"+
    "\3\7\1\45\1\46\16\0\22\7\1\u0100\12\7\5\0"+
    "\3\7\1\45\1\46\16\0\7\7\1\u0101\25\7\5\0"+
    "\3\7\1\45\1\46\16\0\3\7\1\u0102\31\7\5\0"+
    "\3\7\1\45\1\46\16\0\1\7\1\u0103\33\7\5\0"+
    "\3\7\1\45\1\46\16\0\10\7\1\u0104\24\7\5\0"+
    "\3\7\1\45\1\46\16\0\10\7\1\u0105\24\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10759];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\2\11\3\1\4\11\2\1\6\11"+
    "\17\1\1\0\7\1\1\0\1\1\1\11\1\0\26\1"+
    "\1\0\10\1\1\0\32\1\1\11\10\1\1\0\46\1"+
    "\1\11\152\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[261];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  public _MsilLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _MsilLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2262) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 22: 
          { return MsilTokens.INT8_KEYWORD;
          }
        case 65: break;
        case 62: 
          { return MsilTokens.IMPLEMENTS_KEYWORD;
          }
        case 66: break;
        case 39: 
          { return MsilTokens.STRING_KEYWORD;
          }
        case 67: break;
        case 38: 
          { return MsilTokens.STATIC_KEYWORD;
          }
        case 68: break;
        case 8: 
          { return MsilTokens.LT;
          }
        case 69: break;
        case 57: 
          { return MsilTokens._PROPERTY_KEYWORD;
          }
        case 70: break;
        case 59: 
          { return MsilTokens.INTERFACE_KEYWORD;
          }
        case 71: break;
        case 6: 
          { return MsilTokens.LBRACE;
          }
        case 72: break;
        case 25: 
          { return MsilTokens.BRACKET_OUT_KEYWORD;
          }
        case 73: break;
        case 3: 
          { return MsilTokens.PERC;
          }
        case 74: break;
        case 56: 
          { return MsilTokens._ASSEMBLY_KEYWORD;
          }
        case 75: break;
        case 7: 
          { return MsilTokens.RBRACE;
          }
        case 76: break;
        case 11: 
          { return MsilTokens.RBRACKET;
          }
        case 77: break;
        case 34: 
          { return MsilTokens._CLASS_KEYWORD;
          }
        case 78: break;
        case 41: 
          { return MsilTokens.UINT16_KEYWORD;
          }
        case 79: break;
        case 46: 
          { return MsilTokens._CUSTOM_KEYWORD;
          }
        case 80: break;
        case 64: 
          { return MsilTokens.SERIALIZABLE_KEYWORD;
          }
        case 81: break;
        case 13: 
          { return MsilTokens.RPAR;
          }
        case 82: break;
        case 43: 
          { return MsilTokens.UINT32_KEYWORD;
          }
        case 83: break;
        case 36: 
          { return MsilTokens._FIELD_KEYWORD;
          }
        case 84: break;
        case 4: 
          { return MsilTokens.NUMBER;
          }
        case 85: break;
        case 40: 
          { return MsilTokens.SEALED_KEYWORD;
          }
        case 86: break;
        case 54: 
          { return MsilTokens.ABSTRACT_KEYWORD;
          }
        case 87: break;
        case 45: 
          { return MsilTokens.PUBLIC_KEYWORD;
          }
        case 88: break;
        case 23: 
          { return MsilTokens.VOID_KEYWORD;
          }
        case 89: break;
        case 20: 
          { return MsilTokens.COLONCOLON;
          }
        case 90: break;
        case 16: 
          { return MsilTokens.COMMA;
          }
        case 91: break;
        case 29: 
          { return MsilTokens.FINAL_KEYWORD;
          }
        case 92: break;
        case 19: 
          { return MsilTokens.QIDENTIFIER;
          }
        case 93: break;
        case 27: 
          { return MsilTokens.UINT8_KEYWORD;
          }
        case 94: break;
        case 50: 
          { return MsilTokens.FLOAT64_KEYWORD;
          }
        case 95: break;
        case 31: 
          { return MsilTokens.INT64_KEYWORD;
          }
        case 96: break;
        case 51: 
          { return MsilTokens.PRIVATE_KEYWORD;
          }
        case 97: break;
        case 63: 
          { return MsilTokens.SPECIALNAME_KEYWORD;
          }
        case 98: break;
        case 44: 
          { return MsilTokens.OBJECT_KEYWORD;
          }
        case 99: break;
        case 61: 
          { return MsilTokens.VALUETYPE_KEYWORD;
          }
        case 100: break;
        case 17: 
          { return MsilTokens.LINE_COMMENT;
          }
        case 101: break;
        case 10: 
          { return MsilTokens.LBRACKET;
          }
        case 102: break;
        case 2: 
          { return MsilTokens.WHITE_SPACE;
          }
        case 103: break;
        case 48: 
          { return MsilTokens.LITERAL_KEYWORD;
          }
        case 104: break;
        case 26: 
          { return MsilTokens.CLASS_KEYWORD;
          }
        case 105: break;
        case 24: 
          { return MsilTokens.BOOL_KEYWORD;
          }
        case 106: break;
        case 9: 
          { return MsilTokens.GT;
          }
        case 107: break;
        case 33: 
          { return MsilTokens.VALUE_KEYWORD;
          }
        case 108: break;
        case 21: 
          { return MsilTokens.CHAR_KEYWORD;
          }
        case 109: break;
        case 53: 
          { return MsilTokens.ASSEMBLY_KEYWORD;
          }
        case 110: break;
        case 49: 
          { return MsilTokens.EXTENDS_KEYWORD;
          }
        case 111: break;
        case 28: 
          { return MsilTokens.FLOAT_KEYWORD;
          }
        case 112: break;
        case 58: 
          { return MsilTokens.HIDEBYSIG_KEYWORD;
          }
        case 113: break;
        case 30: 
          { return MsilTokens.INT16_KEYWORD;
          }
        case 114: break;
        case 35: 
          { return MsilTokens._EVENT_KEYWORD;
          }
        case 115: break;
        case 32: 
          { return MsilTokens.INT32_KEYWORD;
          }
        case 116: break;
        case 12: 
          { return MsilTokens.LPAR;
          }
        case 117: break;
        case 14: 
          { return MsilTokens.EQ;
          }
        case 118: break;
        case 15: 
          { return MsilTokens.AND;
          }
        case 119: break;
        case 5: 
          { return MsilTokens.IDENTIFIER;
          }
        case 120: break;
        case 55: 
          { return MsilTokens.INITONLY_KEYWORD;
          }
        case 121: break;
        case 18: 
          { return MsilTokens.BLOCK_COMMENT;
          }
        case 122: break;
        case 52: 
          { return MsilTokens.VIRTUAL_KEYWORD;
          }
        case 123: break;
        case 42: 
          { return MsilTokens.UINT64_KEYWORD;
          }
        case 124: break;
        case 37: 
          { return MsilTokens._PARAM_KEYWORD;
          }
        case 125: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 126: break;
        case 47: 
          { return MsilTokens._METHOD_KEYWORD;
          }
        case 127: break;
        case 60: 
          { return MsilTokens.PROTECTED_KEYWORD;
          }
        case 128: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
