/* The following code was generated by JFlex 1.4.3 on 30.11.13 19:54 */

package org.mustbe.consulo.csharp.lang.lexer;

import java.util.*;
import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import org.mustbe.consulo.csharp.lang.psi.CSharpTokens;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 30.11.13 19:54 from the specification file
 * <tt>_CSharpLexer.flex</tt>
 */
class _CSharpLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\13\1\3\1\12\1\0\1\3\1\5\16\13\4\0\1\3\1\0"+
    "\1\10\1\0\1\2\2\0\1\6\1\60\1\61\1\0\1\34\1\64"+
    "\1\34\1\31\1\4\1\21\11\1\1\0\1\63\1\0\1\62\2\0"+
    "\1\11\1\16\1\24\1\16\1\30\1\33\1\26\5\2\1\20\3\2"+
    "\1\36\7\2\1\22\2\2\1\56\1\7\1\57\1\0\1\14\1\0"+
    "\1\50\1\23\1\15\1\27\1\32\1\25\1\43\1\2\1\41\2\2"+
    "\1\17\1\51\1\42\1\47\1\35\1\2\1\45\1\40\1\44\1\37"+
    "\1\46\1\52\1\22\1\53\1\2\1\54\1\0\1\55\1\0\41\13"+
    "\2\0\4\2\4\0\1\2\2\0\1\13\7\0\1\2\4\0\1\2"+
    "\5\0\27\2\1\0\37\2\1\0\u013f\2\31\0\162\2\4\0\14\2"+
    "\16\0\5\2\11\0\1\2\21\0\130\13\5\0\23\13\12\0\1\2"+
    "\13\0\1\2\1\0\3\2\1\0\1\2\1\0\24\2\1\0\54\2"+
    "\1\0\46\2\1\0\5\2\4\0\202\2\1\0\4\13\3\0\105\2"+
    "\1\0\46\2\2\0\2\2\6\0\20\2\41\0\46\2\2\0\1\2"+
    "\7\0\47\2\11\0\21\13\1\0\27\13\1\0\3\13\1\0\1\13"+
    "\1\0\2\13\1\0\1\13\13\0\33\2\5\0\3\2\15\0\4\13"+
    "\14\0\6\13\13\0\32\2\5\0\13\2\16\13\7\0\12\13\4\0"+
    "\2\2\1\13\143\2\1\0\1\2\10\13\1\0\6\13\2\2\2\13"+
    "\1\0\4\13\2\2\12\13\3\2\2\0\1\2\17\0\1\13\1\2"+
    "\1\13\36\2\33\13\2\0\3\2\60\0\46\2\13\13\1\2\u014f\0"+
    "\3\13\66\2\2\0\1\13\1\2\20\13\2\0\1\2\4\13\3\0"+
    "\12\2\2\13\2\0\12\13\21\0\3\13\1\0\10\2\2\0\2\2"+
    "\2\0\26\2\1\0\7\2\1\0\1\2\3\0\4\2\2\0\1\13"+
    "\1\2\7\13\2\0\2\13\2\0\3\13\11\0\1\13\4\0\2\2"+
    "\1\0\3\2\2\13\2\0\12\13\4\2\15\0\3\13\1\0\6\2"+
    "\4\0\2\2\2\0\26\2\1\0\7\2\1\0\2\2\1\0\2\2"+
    "\1\0\2\2\2\0\1\13\1\0\5\13\4\0\2\13\2\0\3\13"+
    "\13\0\4\2\1\0\1\2\7\0\14\13\3\2\14\0\3\13\1\0"+
    "\11\2\1\0\3\2\1\0\26\2\1\0\7\2\1\0\2\2\1\0"+
    "\5\2\2\0\1\13\1\2\10\13\1\0\3\13\1\0\3\13\2\0"+
    "\1\2\17\0\2\2\2\13\2\0\12\13\1\0\1\2\17\0\3\13"+
    "\1\0\10\2\2\0\2\2\2\0\26\2\1\0\7\2\1\0\2\2"+
    "\1\0\5\2\2\0\1\13\1\2\6\13\3\0\2\13\2\0\3\13"+
    "\10\0\2\13\4\0\2\2\1\0\3\2\4\0\12\13\1\0\1\2"+
    "\20\0\1\13\1\2\1\0\6\2\3\0\3\2\1\0\4\2\3\0"+
    "\2\2\1\0\1\2\1\0\2\2\3\0\2\2\3\0\3\2\3\0"+
    "\10\2\1\0\3\2\4\0\5\13\3\0\3\13\1\0\4\13\11\0"+
    "\1\13\17\0\11\13\11\0\1\2\7\0\3\13\1\0\10\2\1\0"+
    "\3\2\1\0\27\2\1\0\12\2\1\0\5\2\4\0\7\13\1\0"+
    "\3\13\1\0\4\13\7\0\2\13\11\0\2\2\4\0\12\13\22\0"+
    "\2\13\1\0\10\2\1\0\3\2\1\0\27\2\1\0\12\2\1\0"+
    "\5\2\2\0\1\13\1\2\7\13\1\0\3\13\1\0\4\13\7\0"+
    "\2\13\7\0\1\2\1\0\2\2\4\0\12\13\22\0\2\13\1\0"+
    "\10\2\1\0\3\2\1\0\27\2\1\0\20\2\4\0\6\13\2\0"+
    "\3\13\1\0\4\13\11\0\1\13\10\0\2\2\4\0\12\13\22\0"+
    "\2\13\1\0\22\2\3\0\30\2\1\0\11\2\1\0\1\2\2\0"+
    "\7\2\3\0\1\13\4\0\6\13\1\0\1\13\1\0\10\13\22\0"+
    "\2\13\15\0\60\2\1\13\2\2\7\13\4\0\10\2\10\13\1\0"+
    "\12\13\47\0\2\2\1\0\1\2\2\0\2\2\1\0\1\2\2\0"+
    "\1\2\6\0\4\2\1\0\7\2\1\0\3\2\1\0\1\2\1\0"+
    "\1\2\2\0\2\2\1\0\4\2\1\13\2\2\6\13\1\0\2\13"+
    "\1\2\2\0\5\2\1\0\1\2\1\0\6\13\2\0\12\13\2\0"+
    "\2\2\42\0\1\2\27\0\2\13\6\0\12\13\13\0\1\13\1\0"+
    "\1\13\1\0\1\13\4\0\2\13\10\2\1\0\42\2\6\0\24\13"+
    "\1\0\2\13\4\2\4\0\10\13\1\0\44\13\11\0\1\13\71\0"+
    "\42\2\1\0\5\2\1\0\2\2\1\0\7\13\3\0\4\13\6\0"+
    "\12\13\6\0\6\2\4\13\106\0\46\2\12\0\51\2\7\0\132\2"+
    "\5\0\104\2\5\0\122\2\6\0\7\2\1\0\77\2\1\0\1\2"+
    "\1\0\4\2\2\0\7\2\1\0\1\2\1\0\4\2\2\0\47\2"+
    "\1\0\1\2\1\0\4\2\2\0\37\2\1\0\1\2\1\0\4\2"+
    "\2\0\7\2\1\0\1\2\1\0\4\2\2\0\7\2\1\0\7\2"+
    "\1\0\27\2\1\0\37\2\1\0\1\2\1\0\4\2\2\0\7\2"+
    "\1\0\47\2\1\0\23\2\16\0\11\13\56\0\125\2\14\0\u026c\2"+
    "\2\0\10\2\12\0\32\2\5\0\113\2\3\0\3\2\17\0\15\2"+
    "\1\0\4\2\3\13\13\0\22\2\3\13\13\0\22\2\2\13\14\0"+
    "\15\2\1\0\3\2\1\0\2\13\14\0\64\2\40\13\3\0\1\2"+
    "\3\0\2\2\1\13\2\0\12\13\41\0\3\13\2\0\12\13\6\0"+
    "\130\2\10\0\51\2\1\13\126\0\35\2\3\0\14\13\4\0\14\13"+
    "\12\0\12\13\36\2\2\0\5\2\u038b\0\154\2\224\0\234\2\4\0"+
    "\132\2\6\0\26\2\2\0\6\2\2\0\46\2\2\0\6\2\2\0"+
    "\10\2\1\0\1\2\1\0\1\2\1\0\1\2\1\0\37\2\2\0"+
    "\65\2\1\0\7\2\1\0\1\2\3\0\3\2\1\0\7\2\3\0"+
    "\4\2\2\0\6\2\4\0\15\2\5\0\3\2\1\0\7\2\17\0"+
    "\4\13\32\0\5\13\20\0\2\2\23\0\1\2\13\0\4\13\6\0"+
    "\6\13\1\0\1\2\15\0\1\2\40\0\22\2\36\0\15\13\4\0"+
    "\1\13\3\0\6\13\27\0\1\2\4\0\1\2\2\0\12\2\1\0"+
    "\1\2\3\0\5\2\6\0\1\2\1\0\1\2\1\0\1\2\1\0"+
    "\4\2\1\0\3\2\1\0\7\2\3\0\3\2\5\0\5\2\26\0"+
    "\44\2\u0e81\0\3\2\31\0\11\2\6\13\1\0\5\2\2\0\5\2"+
    "\4\0\126\2\2\0\2\13\2\0\3\2\1\0\137\2\5\0\50\2"+
    "\4\0\136\2\21\0\30\2\70\0\20\2\u0200\0\u19b6\2\112\0\u51a6\2"+
    "\132\0\u048d\2\u0773\0\u2ba4\2\u215c\0\u012e\2\2\0\73\2\225\0\7\2"+
    "\14\0\5\2\5\0\1\2\1\13\12\2\1\0\15\2\1\0\5\2"+
    "\1\0\1\2\1\0\2\2\1\0\2\2\1\0\154\2\41\0\u016b\2"+
    "\22\0\100\2\2\0\66\2\50\0\15\2\3\0\20\13\20\0\4\13"+
    "\17\0\2\2\30\0\3\2\31\0\1\2\6\0\5\2\1\0\207\2"+
    "\2\0\1\13\4\0\1\2\13\0\12\13\7\0\32\2\4\0\1\2"+
    "\1\0\32\2\12\0\132\2\3\0\6\2\2\0\6\2\2\0\6\2"+
    "\2\0\3\2\3\0\2\2\3\0\2\2\22\0\3\13\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\1\1\3\1\2\1\3\1\7\10\3\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\3\23\1\24\2\5\2\6\1\25\1\3\2\2"+
    "\13\3\1\23\2\25\1\3\1\2\1\0\7\3\1\26"+
    "\1\27\4\3\1\0\1\3\1\30\11\3\1\31\1\32"+
    "\1\3\1\33\1\3\1\34\7\3\1\35\1\36\1\37"+
    "\1\40\2\3\1\41\3\3\1\42\2\3\1\43\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6\0\u031b"+
    "\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\65\0\65\0\65"+
    "\0\65\0\65\0\65\0\65\0\65\0\65\0\65\0\65"+
    "\0\65\0\u0459\0\u048e\0\u04c3\0\65\0\u04f8\0\u052d\0\65"+
    "\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636\0\u066b\0\u06a0\0\u06d5"+
    "\0\u070a\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813\0\u0848\0\u087d"+
    "\0\u08b2\0\65\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0"+
    "\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\237\0\u0b2e\0\u0b63"+
    "\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\237\0\u0c6c\0\u0ca1\0\u0cd6"+
    "\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\237\0\237"+
    "\0\u0e49\0\237\0\u0e7e\0\237\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52"+
    "\0\u0f87\0\u0fbc\0\u0ff1\0\237\0\237\0\237\0\237\0\u1026"+
    "\0\u105b\0\237\0\u1090\0\u10c5\0\u10fa\0\237\0\u112f\0\u1164"+
    "\0\237\0\237";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\2"+
    "\1\10\1\11\1\5\1\2\1\4\1\12\3\4\1\13"+
    "\5\4\1\14\1\4\1\15\1\16\1\4\1\2\1\17"+
    "\1\4\1\20\1\21\1\22\1\23\1\4\1\24\1\4"+
    "\1\25\5\4\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\66\0\1\3\12\0\1\3\2\0"+
    "\2\37\1\3\3\0\2\40\2\41\1\42\2\43\32\0"+
    "\2\4\10\0\16\4\1\0\2\4\1\0\17\4\14\0"+
    "\1\5\1\0\1\5\4\0\1\5\56\0\1\44\60\0"+
    "\5\7\1\0\1\45\1\46\2\7\1\0\52\7\5\10"+
    "\1\0\1\10\1\47\1\50\1\10\1\0\52\10\10\0"+
    "\1\51\55\0\2\4\10\0\4\4\1\52\11\4\1\0"+
    "\2\4\1\0\17\4\12\0\1\3\12\0\1\3\2\0"+
    "\2\37\1\3\1\53\2\54\2\40\2\41\1\42\2\43"+
    "\32\0\2\4\10\0\16\4\1\0\1\55\1\4\1\0"+
    "\17\4\12\0\1\42\17\0\1\42\44\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\5\4\1\56\3\4\1\57"+
    "\5\4\12\0\2\4\10\0\16\4\1\0\2\4\1\0"+
    "\2\4\1\60\14\4\12\0\2\4\10\0\16\4\1\0"+
    "\2\4\1\0\3\4\1\61\13\4\12\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\7\4\1\62\7\4\12\0"+
    "\2\4\10\0\16\4\1\0\2\4\1\0\5\4\1\63"+
    "\11\4\12\0\2\4\10\0\16\4\1\0\1\64\1\4"+
    "\1\0\13\4\1\65\3\4\12\0\2\4\10\0\16\4"+
    "\1\0\2\4\1\0\16\4\1\66\12\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\12\4\1\67\4\4\12\0"+
    "\1\42\12\0\1\42\4\0\1\42\3\0\2\40\2\41"+
    "\1\0\2\43\32\0\1\70\12\0\1\70\4\0\1\70"+
    "\3\0\2\40\2\41\3\0\1\70\30\0\5\44\1\0"+
    "\4\44\1\0\52\44\5\7\1\0\4\7\1\0\52\7"+
    "\5\10\1\0\4\10\1\0\52\10\5\51\1\0\1\51"+
    "\1\71\1\72\54\51\1\0\2\4\10\0\16\4\1\0"+
    "\2\4\1\0\13\4\1\73\3\4\12\0\1\74\12\0"+
    "\3\74\2\37\1\74\1\0\6\74\1\75\2\74\14\0"+
    "\1\74\15\0\1\54\12\0\1\54\2\0\2\37\1\54"+
    "\44\0\2\4\10\0\4\4\1\76\11\4\1\0\2\4"+
    "\1\0\17\4\12\0\2\4\10\0\16\4\1\0\2\4"+
    "\1\0\2\4\1\77\14\4\12\0\2\4\10\0\16\4"+
    "\1\0\1\100\1\4\1\0\17\4\12\0\2\4\10\0"+
    "\10\4\1\101\5\4\1\0\2\4\1\0\17\4\12\0"+
    "\2\4\10\0\16\4\1\0\2\4\1\0\4\4\1\102"+
    "\12\4\12\0\2\4\10\0\16\4\1\0\2\4\1\0"+
    "\10\4\1\103\2\4\1\104\3\4\12\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\7\4\1\105\7\4\12\0"+
    "\2\4\10\0\16\4\1\0\2\4\1\0\15\4\1\106"+
    "\1\4\12\0\2\4\10\0\16\4\1\0\2\4\1\0"+
    "\14\4\1\107\2\4\12\0\2\4\10\0\16\4\1\0"+
    "\2\4\1\0\1\110\16\4\12\0\2\4\10\0\16\4"+
    "\1\0\2\4\1\0\4\4\1\111\12\4\12\0\1\70"+
    "\12\0\1\70\4\0\1\70\3\0\2\40\2\41\34\0"+
    "\5\51\1\0\4\51\1\0\52\51\1\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\3\4\1\112\13\4\12\0"+
    "\1\74\12\0\3\74\2\37\1\74\1\0\6\74\1\113"+
    "\2\74\1\0\2\43\11\0\1\74\15\0\1\113\12\0"+
    "\3\113\2\0\1\113\1\0\6\113\1\0\2\113\14\0"+
    "\1\113\15\0\2\4\10\0\16\4\1\0\1\114\1\4"+
    "\1\0\17\4\12\0\2\4\10\0\16\4\1\0\2\4"+
    "\1\0\14\4\1\115\2\4\12\0\2\4\10\0\16\4"+
    "\1\0\2\4\1\0\5\4\1\116\11\4\12\0\2\4"+
    "\10\0\4\4\1\117\11\4\1\0\2\4\1\0\17\4"+
    "\12\0\2\4\10\0\16\4\1\0\2\4\1\0\5\4"+
    "\1\120\11\4\12\0\2\4\10\0\16\4\1\0\2\4"+
    "\1\0\2\4\1\121\1\4\1\122\12\4\12\0\2\4"+
    "\10\0\16\4\1\0\2\4\1\0\7\4\1\123\7\4"+
    "\12\0\2\4\10\0\16\4\1\0\1\124\1\4\1\0"+
    "\17\4\12\0\2\4\10\0\16\4\1\0\1\125\1\4"+
    "\1\0\17\4\12\0\2\4\10\0\16\4\1\0\1\126"+
    "\1\4\1\0\17\4\12\0\2\4\10\0\14\4\1\127"+
    "\1\4\1\0\2\4\1\0\17\4\12\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\3\4\1\130\13\4\12\0"+
    "\1\113\12\0\3\113\2\0\1\113\1\0\6\113\1\0"+
    "\2\113\1\0\2\43\11\0\1\113\15\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\6\4\1\131\10\4\12\0"+
    "\2\4\10\0\16\4\1\0\2\4\1\0\7\4\1\132"+
    "\7\4\12\0\2\4\10\0\16\4\1\0\2\4\1\0"+
    "\4\4\1\133\12\4\12\0\2\4\10\0\16\4\1\0"+
    "\2\4\1\0\6\4\1\134\10\4\12\0\2\4\10\0"+
    "\2\4\1\135\13\4\1\0\2\4\1\0\17\4\12\0"+
    "\2\4\10\0\16\4\1\0\2\4\1\0\5\4\1\136"+
    "\11\4\12\0\2\4\10\0\16\4\1\0\2\4\1\0"+
    "\4\4\1\137\12\4\12\0\2\4\10\0\16\4\1\0"+
    "\2\4\1\0\10\4\1\140\6\4\12\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\3\4\1\141\13\4\12\0"+
    "\2\4\10\0\16\4\1\0\2\4\1\0\12\4\1\142"+
    "\4\4\12\0\2\4\10\0\16\4\1\0\2\4\1\0"+
    "\13\4\1\143\3\4\12\0\2\4\10\0\2\4\1\144"+
    "\13\4\1\0\2\4\1\0\17\4\12\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\7\4\1\145\7\4\12\0"+
    "\2\4\10\0\16\4\1\0\2\4\1\0\6\4\1\146"+
    "\10\4\12\0\2\4\10\0\2\4\1\147\13\4\1\0"+
    "\2\4\1\0\17\4\12\0\2\4\10\0\12\4\1\150"+
    "\3\4\1\0\2\4\1\0\17\4\12\0\2\4\10\0"+
    "\16\4\1\0\2\4\1\0\1\151\16\4\12\0\2\4"+
    "\10\0\12\4\1\152\3\4\1\0\2\4\1\0\17\4"+
    "\12\0\2\4\10\0\16\4\1\0\2\4\1\0\7\4"+
    "\1\153\7\4\12\0\2\4\10\0\16\4\1\0\2\4"+
    "\1\0\13\4\1\154\3\4\12\0\2\4\10\0\16\4"+
    "\1\0\2\4\1\0\13\4\1\155\3\4\12\0\2\4"+
    "\10\0\16\4\1\0\1\156\1\4\1\0\17\4\12\0"+
    "\2\4\10\0\2\4\1\157\13\4\1\0\2\4\1\0"+
    "\17\4\12\0\2\4\10\0\2\4\1\160\13\4\1\0"+
    "\2\4\1\0\17\4\12\0\2\4\10\0\16\4\1\0"+
    "\1\161\1\4\1\0\17\4\12\0\2\4\10\0\16\4"+
    "\1\0\1\162\1\4\1\0\17\4\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4505];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\23\1\14\11\3\1\1\11\2\1\1\11"+
    "\21\1\1\11\2\1\1\0\15\1\1\0\47\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  _CSharpLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _CSharpLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1778) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 11: 
          { return CSharpTokens.RBRACKET;
          }
        case 37: break;
        case 34: 
          { return CSharpTokens.DELEGATE_KEYWORD;
          }
        case 38: break;
        case 24: 
          { return CSharpTokens.ENUM_KEYWORD;
          }
        case 39: break;
        case 19: 
          { return CSharpTokens.DOUBLE_LITERAL;
          }
        case 40: break;
        case 29: 
          { return CSharpTokens.PUBLIC_KEYWORD;
          }
        case 41: break;
        case 7: 
          { return CSharpTokens.DOT;
          }
        case 42: break;
        case 17: 
          { return CSharpTokens.LONG_LITERAL;
          }
        case 43: break;
        case 30: 
          { return CSharpTokens.STRUCT_KEYWORD;
          }
        case 44: break;
        case 14: 
          { return CSharpTokens.EQ;
          }
        case 45: break;
        case 26: 
          { return CSharpTokens.CLASS_KEYWORD;
          }
        case 46: break;
        case 15: 
          { return CSharpTokens.SEMICOLON;
          }
        case 47: break;
        case 12: 
          { return CSharpTokens.LPAR;
          }
        case 48: break;
        case 18: 
          { return CSharpTokens.FLOAT_LITERAL;
          }
        case 49: break;
        case 25: 
          { return CSharpTokens.VOID_KEYWORD;
          }
        case 50: break;
        case 10: 
          { return CSharpTokens.LBRACKET;
          }
        case 51: break;
        case 3: 
          { return CSharpTokens.IDENTIFIER;
          }
        case 52: break;
        case 5: 
          { return CSharpTokens.CHARACTER_LITERAL;
          }
        case 53: break;
        case 22: 
          { return CSharpTokens.INT_KEYWORD;
          }
        case 54: break;
        case 4: 
          { return CSharpTokens.WHITE_SPACE;
          }
        case 55: break;
        case 20: 
          { return CSharpTokens.LINE_COMMENT;
          }
        case 56: break;
        case 16: 
          { return CSharpTokens.COMMA;
          }
        case 57: break;
        case 21: 
          { return CSharpTokens.VERBATIM_STRING_LITERAL;
          }
        case 58: break;
        case 13: 
          { return CSharpTokens.RPAR;
          }
        case 59: break;
        case 2: 
          { return CSharpTokens.INTEGER_LITERAL;
          }
        case 60: break;
        case 33: 
          { return CSharpTokens.TYPEOF_KEYWORD;
          }
        case 61: break;
        case 8: 
          { return CSharpTokens.LBRACE;
          }
        case 62: break;
        case 9: 
          { return CSharpTokens.RBRACE;
          }
        case 63: break;
        case 32: 
          { return CSharpTokens.STATIC_KEYWORD;
          }
        case 64: break;
        case 36: 
          { return CSharpTokens.NAMESPACE_KEYWORD;
          }
        case 65: break;
        case 31: 
          { return CSharpTokens.STRING_KEYWORD;
          }
        case 66: break;
        case 6: 
          { return CSharpTokens.STRING_LITERAL;
          }
        case 67: break;
        case 35: 
          { return CSharpTokens.INTERFACE_KEYWORD;
          }
        case 68: break;
        case 1: 
          { return CSharpTokens.BAD_CHARACTER;
          }
        case 69: break;
        case 27: 
          { return CSharpTokens.EVENT_KEYWORD;
          }
        case 70: break;
        case 28: 
          { return CSharpTokens.USING_KEYWORD;
          }
        case 71: break;
        case 23: 
          { return CSharpTokens.NEW_KEYWORD;
          }
        case 72: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
